config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#welcome'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get 'welcome', to: "pages#welcome"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no, maximum-scale=1.0">
    <meta name="description" content="Animated 404 Error Page">
    <meta name="author" content="rakesh535">
    <meta name="keywords" content="404, css3, html5, animated, animated bubble, template">
    <title>Evolt</title>

    <%= favicon_link_tag 'logo_transparent_background_cropped.png' %>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <!-- 3.0 CSS IMPORT -->

    <!-- CSS IMPORT FOR FONT -->
    <link href='https://fonts.googleapis.com/css?family=Oswald:400,300' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>
      <!-- Favicons -->
    <link href="img/favicon.png" rel="icon">
    <link href="img/apple-touch-icon.png" rel="apple-touch-icon">
  </head>
  <body>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <!-- JavaScript Libraries -->
    <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script> -->
    <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-migrate/3.0.1/jquery-migrate.min.js"></script> -->
    <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script> -->
    <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.hoverintent/1.10.0/jquery.hoverIntent.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/superfish/1.7.10/js/superfish.min.js"></script> -->
    <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/wow/1.1.2/wow.min.js"></script> -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/waypoints/4.0.1/noframework.waypoints.min.js"></script>
    <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/Counter-Up/1.0.0/jquery.counterup.min.js"></script> -->
    <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"></script> -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.isotope/3.0.6/isotope.pkgd.min.js"></script>
    <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.10.0/js/lightbox.min.js"></script> -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/web-animations/2.2.2/web-animations.min.js"></script>
    <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.touchswipe/1.6.19/jquery.touchSwipe.min.js"></script> -->
  </body>
</html>

app/views/pages/home.html.erb
<div class="evolt-banner">
<%= render 'shared/navbarhidden' %>
  <div class="evolt-banner-container">
    <!-- 6.0 wrapper -->
    <canvas class="spirit-bubbles" id="canvas"></canvas>
    <div class="wrapper" id="wrapper-large">
      <div class="container-fluid">
        <div class="row">
          <div class="col-sm-12 text-center">
            <!-- 6.1 SPIRIT BUBBLES CANVAS -->
            <!-- end SPIRIT BUBBLES CANVAS -->

            <div class="evolt-logo-container">
              <div class="evolt-log"></div>
            </div>
            <!-- end HOME & RETURN BUTTONS -->

            <!-- 6.3 ERROR CODE -->
            <h1 class="wow flipInY" data-wow-delay="1.5s">Strategic error</h1>
            <!-- ERROR TEXT, Change error text according to your requirement -->
            <h2 id="sub-title"></h2>
            <!-- ROTATING TEXT -->
            <!-- END ERROR CODE -->

            <!-- 6.4 search-form -->
<!--             <form class="form-inline search-form">
              <div class="input-group">
                <input type="type" class="form-control" placeholder="search the web">
                <span class="input-group-btn">
                  <button type="submit" class="btn"><span class="search-icon"></span></button>
                </span>
              </div>
            </form> -->
            <!-- end search-form -->
            <!-- 6.2 HOME & RETURN BUTTONS -->
            <ul class="return-btn center-block">
              <li>
                <%= link_to welcome_path, class: 'wow slideInLeft' do %>
                  Home
                  <span class="icons-container">
                    <span class="home-icon">
                    </span>
                  </span>
                <% end %>
              </li>
              <li>
                <%= link_to welcome_path(:anchor => "services"), class: 'wow slideInRight' do %>
                  About Evolt
                  <span class="icons-container">
                    <span class="home-icon">
                    </span>
                  </span>
                <% end %>
              </li>
            </ul>

            <!-- 6.5 social-icons -->
            <ul class="social-icons center-block">
              <li>
                <a class="hvr-icon-wobble-vertical wow slideInLeft" data-wow-delay="3.5s" href="#">E</a>
              </li>
              <li>
                <a class="hvr-icon-wobble-vertical wow slideInLeft" data-wow-delay="2.5s" href="#">V</a>
              </li>
              <li>
                <a class="hvr-icon-wobble-vertical wow fadeIn" data-wow-delay="2s" href="#">O</a>
              </li>
              <li>
                <a class="hvr-icon-wobble-vertical wow slideInRight" data-wow-delay="2.5s" href="#">L</a>
              </li>
              <li>
                <a class="hvr-icon-wobble-vertical wow slideInRight" data-wow-delay="3.5s" href="#">T</a>
              </li>
            </ul>
            <!-- end social-icons -->
          </div>
        </div>
      </div>
    </div>
    <!-- end wrapper -->
  </div>
</div>

app/views/shared/_navbar.html.erb
  <!--==========================
    Header
  ============================-->
  <header id="header">
    <div class="container-fluid">

      <div id="logo" class="pull-left">
  <!--       <h1><a href="#intro" class="scrollto">BizPage</a></h1> -->
        <!-- Uncomment below if you prefer to use an image logo -->
        <!-- <a href="#intro"><img src="img/logo.png" alt="" title="" /></a>-->
      </div>

      <nav id="nav-menu-container">
        <ul class=" nav-menu">
          <li class="menu-active"><a href="#home">Home</a></li>
          <li><a href="#services">About Us</a></li>
          <li><a href="#about">Values</a></li>
          <li><a href="#cases">Use cases</a></li>
          <li><a href="#partners">Partners</a></li>
          <li><a href="#contact">Contact</a></li>
        </ul>
      </nav><!-- #nav-menu-container -->
    </div>
  </header><!-- #header -->

app/views/shared/_navbarhidden.html.erb
  <!--==========================
    Header
  ============================-->
  <header id="header">
    <div class="container-fluid">

      <div id="logo" class="pull-left">
  <!--       <h1><a href="#intro" class="scrollto">BizPage</a></h1> -->
        <!-- Uncomment below if you prefer to use an image logo -->
        <!-- <a href="#intro"><img src="img/logo.png" alt="" title="" /></a>-->
        <%= image_tag("logo_transparent_background_cropped.png", :alt => "logo", :class => "evolt-logo-cropped") %>
      </div>

<!--       <nav id="nav-menu-container">
        <ul class="nav-menu">
          <li class="menu-active"><a href="#intro">Home</a></li>
          <li><a href="#about"></a></li>
          <li><a href="#services">Services</a></li>
          <li><a href="#portfolio">Portfolio</a></li>
          <li><a href="#team">Team</a></li>
          <li class="menu-has-children"><a href="">Drop Down</a>
            <ul>
              <li><a href="#">Drop Down 1</a></li>
              <li><a href="#">Drop Down 3</a></li>
              <li><a href="#">Drop Down 4</a></li>
              <li><a href="#">Drop Down 5</a></li>
            </ul>
          </li>
          <li><a href="#contact">Contact</a></li>
        </ul>
      </nav> --><!-- #nav-menu-container -->
    </div>
  </header><!-- #header -->